# Exploratory Data Analysis (continued...)

In [1]:
import pandas as pd

## Pandas Indexing

### 1. Label-based Indexing --> loc
It is used to access data using rows and columns labels (names)

In [53]:
# Creating a sample DataFrame
data = {
    'Name': ['Ali', 'Sara', 'Bilal', 'Ahsan', 'Hina'],
    'Age': [23, 25, 22, 24, 26],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Multan', 'Quetta'],
    'Marks': [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])

In [54]:
df

    Name  Age       City  Marks
a    Ali   23     Lahore     85
b   Sara   25    Karachi     90
c  Bilal   22  Islamabad     78
d  Ahsan   24     Multan     88
e   Hina   26     Quetta     92

#### a. Selecting a single row

In [55]:
df.loc['b']

Name        Sara
Age           25
City     Karachi
Marks         90
Name: b, dtype: object

#### b. Selecting multiple rows by labels

In [57]:
df.loc[['a', 'd', 'e']]

    Name  Age    City  Marks
a    Ali   23  Lahore     85
d  Ahsan   24  Multan     88
e   Hina   26  Quetta     92

##### c. Selecting specific columns

In [58]:
df.loc[:, ['Name', 'City']]

    Name       City
a    Ali     Lahore
b   Sara    Karachi
c  Bilal  Islamabad
d  Ahsan     Multan
e   Hina     Quetta

#### d. Selecting specific rows and columns

In [59]:
df.loc[['a', 'b', 'd'], ['Name', 'City']]

    Name     City
a    Ali   Lahore
b   Sara  Karachi
d  Ahsan   Multan

### 2. Integer location based indexing --> iloc
It is used to access data based on rows and columns numbers instead of labels

#### a. Select row by position

In [60]:
df.iloc[2]

Name         Bilal
Age             22
City     Islamabad
Marks           78
Name: c, dtype: object

#### b. Selecting multiple rows

In [61]:
df.iloc[[0,3,4]]

    Name  Age    City  Marks
a    Ali   23  Lahore     85
d  Ahsan   24  Multan     88
e   Hina   26  Quetta     92

#### c. Select specific rows and columns

In [62]:
df.iloc[[0,3,4], [0,2]]

    Name    City
a    Ali  Lahore
d  Ahsan  Multan
e   Hina  Quetta

#### d. Select rows and columns slices

In [64]:
df.iloc[2:5, 0:3]

    Name  Age       City
c  Bilal   22  Islamabad
d  Ahsan   24     Multan
e   Hina   26     Quetta

## Now we are loading our real dataset for EDA

In [65]:
bmi_data = pd.read_csv("bmi_modified.csv")
bmi_data.head()

   Gender  Height  Weight  Index  Height_m        BMI     Categories
0    Male     174      96      4      1.74  31.708284  Obese Class I
1    Male     189      87      2      1.89  24.355421         Normal
2  Female     185     110      4      1.85  32.140248  Obese Class I
3  Female     195     104      3      1.95  27.350427     Overweight
4    Male     149      61      3      1.49  27.476240     Overweight

Built-in Statistical methods:  
1.  .median() --> Middle value when data is sorted (not affected much by outliers)  
2.  .mean()  --> Arithmetic Average (sensitive to extreme values)  
3.  .mode()  
4.  .min()  
5.  .max()  
6.  .var()  
7.  .std()  
8.  .sum()  
9.  .quantile()

In [3]:
bmi_data.describe()

           Height      Weight       Index    Height_m         BMI
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean   169.944000  106.000000    3.748000    1.699440   37.765284
std     16.375261   32.382607    1.355053    0.163753   13.965620
min    140.000000   50.000000    0.000000    1.400000   12.753801
25%    156.000000   80.000000    3.000000    1.560000   27.169353
50%    170.500000  106.000000    4.000000    1.705000   36.956941
75%    184.000000  136.000000    5.000000    1.840000   46.390467
max    199.000000  160.000000    5.000000    1.990000   78.853402

## Aggregating:  
Aggregation is the process of collecting and summarizing data — for example, finding the average, total, maximum, or count for each group in a dataset.

In [8]:
# mean
mean = bmi_data["Height"].mean()
print(f"Mean: {mean}")
# median
median = bmi_data["Height"].median()
print(f"Median: {median}")
# standard deviation
std = bmi_data["Height"].std()
print(f"Standard Deviation: {std}")
# variance
var = bmi_data["Height"].var()
print(f"Variance: {var}")
# minimum value
Min = bmi_data["Height"].min()
print(f"Minumum value: {Min}")
# maximum value
Max = bmi_data["Height"].max()
print(f"Maximum value: {Max}")
# summation
Sum = bmi_data["Height"].sum()
print(f"Sum: {Sum}")
# count np.of values in a column
cnt = bmi_data["Height"].count()
print(f"No. of values in Height column: {cnt}")
# count rows in Height column with Height > 150
count_ = bmi_data[bmi_data["Height"] > 150].count()
print(count_)

Mean: 169.944
Median: 170.5
Standard Deviation: 16.375260679593755
Variance: 268.1491623246493
Minumum value: 140
Maximum value: 199
Sum: 84972
No. of values in Height column: 500
Gender        421
Height        421
Weight        421
Index         421
Height_m      421
BMI           421
Categories    421
dtype: int64

In [9]:
bmi_data["Height"].count()

500

## Quantile: 
A quantile is a cut point that divides a dataset into equal-sized groups based on the value of the data.

Quantile helps you to understant how your data is distributed - they tell you where most of the data lies and how it is spread out.

If we divide our data in 4 equal parts then each group = 25% of the data

Consider a data:

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]   ---> Data

Q1 (25th percentile)  --> 30    (25% percent of data below this point)  
Q2 (50th percentile or median)  --> 55   (50% percent of data below this point)  
Q3 (75th percentile)  --> 80    (75% percent of data below this point)

In [5]:
# 50% quantile -- default
quantile_50_per = bmi_data["Height"].quantile()
print(f"50% Quantile: {quantile_50_per}")
# 25% quantile 
quantile_25_per = bmi_data["Height"].quantile(q=0.25)
print(f"25% Quantile: {quantile_25_per}")
# 75% quantile
quantile_75_per = bmi_data["Height"].quantile(q=0.75)
print(f"75% Quantile: {quantile_75_per}")

50% Quantile: 170.5
25% Quantile: 156.0
75% Quantile: 184.0

.agg() methods: 
It allows you to apply function or a list of function names to be executed along one of the axis of the dataframe

In [12]:
# apply aggregation to all columns
df = pd.DataFrame({
    "Height": [150, 160, 172],
    "Weight": [70, 65, 44]
})
print(df)

print(df.agg(["min", "max", "std", "var"]))

   Height  Weight
0     150      70
1     160      65
2     172      44
         Height      Weight
min  150.000000   44.000000
max  172.000000   70.000000
std   11.015141   13.796135
var  121.333333  190.333333

Column specific Aggregations

In [13]:
# apply aggregation to specific column
bmi_data["Height"].agg(["min", "max", "std", "var"])

min    140.000000
max    199.000000
std     16.375261
var    268.149162
Name: Height, dtype: float64

In [14]:
# apply aggregation to specific columns
bmi_data.agg({
    "Height": ["min", "max"],
    "Weight": ["std", "var", "count"]
})

       Height       Weight
min     140.0          NaN
max     199.0          NaN
std       NaN    32.382607
var       NaN  1048.633267
count     NaN   500.000000

# Grouping

groupby() 
this method is used to split data into groups based on some column(s), then apply aggregation functions and finally combine the results

Split --> Apply --> Combine

In [21]:
bmi_data

     Gender  Height  Weight  Index  Height_m        BMI      Categories
0      Male     174      96      4      1.74  31.708284   Obese Class I
1      Male     189      87      2      1.89  24.355421          Normal
2    Female     185     110      4      1.85  32.140248   Obese Class I
3    Female     195     104      3      1.95  27.350427      Overweight
4      Male     149      61      3      1.49  27.476240      Overweight
..      ...     ...     ...    ...       ...        ...             ...
495  Female     150     153      5      1.50  68.000000  Obese Class II
496  Female     184     121      4      1.84  35.739603  Obese Class II
497  Female     141     136      5      1.41  68.407022  Obese Class II
498    Male     150      95      5      1.50  42.222222  Obese Class II
499    Male     173     131      5      1.73  43.770256  Obese Class II

[500 rows x 7 columns]

In [24]:
grouped = bmi_data.groupby("Gender")
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002B44A7E4FD0>

In [27]:
print(grouped["Height"].max())
print(grouped["Weight"].mean())

Gender
Female    199
Male      199
Name: Height, dtype: int64
Gender
Female    105.698039
Male      106.314286
Name: Weight, dtype: float64

In [28]:
# multiple columns
print(grouped[["Height", "Weight"]].max())

        Height  Weight
Gender
Female     199     160
Male       199     160

In [30]:
print(grouped.agg({
    "Height": ["min", "max"],
    "Weight": ["std", "var", "count"]
}))

       Height          Weight
          min  max        std          var count
Gender
Female    140  199  32.962025  1086.495075   255
Male      140  199  31.832734  1013.322951   245

In [31]:
# function to return 30% quantile
def quantile_30(column):
    return column.quantile(0.3)

def quantile_40(column):
    return column.quantile(0.4)

In [32]:
bmi_data["Height"].agg([quantile_30, quantile_40])

quantile_30    159.0
quantile_40    165.0
Name: Height, dtype: float64

Cumulative sum

In [33]:
bmi_data["Height"].cumsum()

0        174
1        363
2        548
3        743
4        892
       ...
495    84324
496    84508
497    84649
498    84799
499    84972
Name: Height, Length: 500, dtype: int64

In [34]:
# cumulative max --> cummax()  keep track of the maximum value up to the current row
# biggest number so far
#df = pd.Series([1,2,3,4,5])
df = pd.Series([5,4,3,2,1])
print(df.cummax())

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [35]:
# cummulative min --> cummin()  kepp track of the minimum value up to the current row
# smallest number so far
#df = pd.Series([1,2,3,4,5])
df = pd.Series([5,4,3,2,1])
print(df.cummin())

0    5
1    4
2    3
3    2
4    1
dtype: int64

In [36]:
# cummulative product --> cumprod()  Multiples values step by step (like running multiplication)
# product so far
df = pd.Series([1,2,3,4,5])

print(df.cumprod())

0      1
1      2
2      6
3     24
4    120
dtype: int64

Note: These methods are used to show trends in stock market (max price so far), weather data (minimum temperature so far)

In [48]:
g = bmi_data.groupby(["Gender", "Categories"])

In [49]:
g.mean()

                           Height      Weight     Index  Height_m        BMI
Gender Categories
Female Normal          171.894737   65.000000  1.947368  1.718947  21.913129
       Obese Class I   172.405405   97.324324  3.891892  1.724054  32.418186
       Obese Class II  165.500000  130.438462  4.707692  1.655000  48.317460
       Overweight      177.027027   86.702703  2.945946  1.770270  27.462536
       Underweight     187.076923   55.153846  0.538462  1.870769  15.841626
Male   Normal          178.035714   72.250000  2.000000  1.780357  22.666995
       Obese Class I   177.250000  103.428571  3.964286  1.772500  32.640791
       Obese Class II  162.729927  126.116788  4.766423  1.627299  48.101743
       Overweight      174.645161   85.322581  3.000000  1.746452  27.756955
       Underweight     186.095238   57.380952  0.714286  1.860952  16.577282