# Data Cleaning:
Data cleaning in the process of identifying and correcting (or removuing) errors, missing values in your dataset so that your analysis is reliable

Data cleaning workflow:

This workflow covers almost every common cleaning scenario:

a. Missing data  
b. Duplicates  
c. Special characters  
d. Invalid values  
e. Inconsistent text  
f. Correct data types

In [1]:
import pandas as pd
import numpy as np

In [4]:
# creating dummy data (with special charactors, missing values, duplicates, and invalid data)

data = {
    'Name': ['Alice ', '@Bob', 'Charlie$', 'David#', 'Eve%', 'Frank*', 'Alice ', np.nan],
    'Age': [25, np.nan, 35, 45, 28, -5, 25, 30],
    'Gender': ['Female', 'Male', 'Male', np.nan, 'Female', 'Male', 'Female', 'male'],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', np.nan, 'Chicago', 'New York', 'Los Angeles'],
    'Salary': [50000, 60000, np.nan, 80000, 56000, 70000, 50000, 60000],
    'Comment': ['Good job!', 'Needs improvement  ', 'Paid $100', '50% discount', 'Excellent!!', 'Check* this', 'Good job!', '😊 Excellent']
}

In [5]:
df = pd.DataFrame(data)
df

       Name   Age  Gender         City   Salary              Comment
0    Alice   25.0  Female     New York  50000.0            Good job!
1      @Bob   NaN    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.0    Male     New York      NaN            Paid $100
3    David#  45.0     NaN      Chicago  80000.0         50% discount
4      Eve%  28.0  Female          NaN  56000.0          Excellent!!
5    Frank*  -5.0    Male      Chicago  70000.0          Check* this
6    Alice   25.0  Female     New York  50000.0            Good job!
7       NaN  30.0    male  Los Angeles  60000.0          😊 Excellent

## Step 1: inspect the data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     7 non-null      object
 1   Age      7 non-null      float64
 2   Gender   7 non-null      object
 3   City     7 non-null      object
 4   Salary   7 non-null      float64
 5   Comment  8 non-null      object
dtypes: float64(2), object(4)
memory usage: 512.0+ bytes

In [7]:
df.describe(include='all')

          Name        Age  Gender      City        Salary    Comment
count        7   7.000000       7         7      7.000000          8
unique       6        NaN       3         3           NaN          7
top     Alice         NaN  Female  New York           NaN  Good job!
freq         2        NaN       3         3           NaN          2
mean       NaN  26.142857     NaN       NaN  60857.142857        NaN
std        NaN  15.410263     NaN       NaN  10884.676866        NaN
min        NaN  -5.000000     NaN       NaN  50000.000000        NaN
25%        NaN  25.000000     NaN       NaN  53000.000000        NaN
50%        NaN  28.000000     NaN       NaN  60000.000000        NaN
75%        NaN  32.500000     NaN       NaN  65000.000000        NaN
max        NaN  45.000000     NaN       NaN  80000.000000        NaN

In [8]:
df.isnull()

    Name    Age  Gender   City  Salary  Comment
0  False  False   False  False   False    False
1  False   True   False  False   False    False
2  False  False   False  False    True    False
3  False  False    True  False   False    False
4  False  False   False   True   False    False
5  False  False   False  False   False    False
6  False  False   False  False   False    False
7   True  False   False  False   False    False

In [9]:
df.isnull().sum()

Name       1
Age        1
Gender     1
City       1
Salary     1
Comment    0
dtype: int64

## Step 2: drop duplicates

removes exact duplicate rows

In [10]:
df

       Name   Age  Gender         City   Salary              Comment
0    Alice   25.0  Female     New York  50000.0            Good job!
1      @Bob   NaN    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.0    Male     New York      NaN            Paid $100
3    David#  45.0     NaN      Chicago  80000.0         50% discount
4      Eve%  28.0  Female          NaN  56000.0          Excellent!!
5    Frank*  -5.0    Male      Chicago  70000.0          Check* this
6    Alice   25.0  Female     New York  50000.0            Good job!
7       NaN  30.0    male  Los Angeles  60000.0          😊 Excellent

In [11]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [12]:
df.duplicated().sum()

1

In [13]:
df = df.drop_duplicates()

In [14]:
df

       Name   Age  Gender         City   Salary              Comment
0    Alice   25.0  Female     New York  50000.0            Good job!
1      @Bob   NaN    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.0    Male     New York      NaN            Paid $100
3    David#  45.0     NaN      Chicago  80000.0         50% discount
4      Eve%  28.0  Female          NaN  56000.0          Excellent!!
5    Frank*  -5.0    Male      Chicago  70000.0          Check* this
7       NaN  30.0    male  Los Angeles  60000.0          😊 Excellent

## Handling missing Values

Drop rows with missing critical values

In [17]:
df = df.dropna(subset=['Name', 'Gender'])   # by default axis = 0  (rows)

In [18]:
df

       Name   Age  Gender         City   Salary              Comment
0    Alice   25.0  Female     New York  50000.0            Good job!
1      @Bob   NaN    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.0    Male     New York      NaN            Paid $100
4      Eve%  28.0  Female          NaN  56000.0          Excellent!!
5    Frank*  -5.0    Male      Chicago  70000.0          Check* this

df = df.dropna(axis=1)    # drop columns having NaN valuses

Fill missing values

Note: It is not feasible to used .loc for filling missin values, because in this we have to provide specific row and column labels. 
Instead of this we automate the process using fillna method. 
1. It find NaN value in the column 
2. Replace the value with the specified value

In [19]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [20]:
df

       Name    Age  Gender         City   Salary              Comment
0    Alice   25.00  Female     New York  50000.0            Good job!
1      @Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.00    Male     New York      NaN            Paid $100
4      Eve%  28.00  Female          NaN  56000.0          Excellent!!
5    Frank*  -5.00    Male      Chicago  70000.0          Check* this

In [21]:
df['City'] = df['City'].fillna('unknown')

In [25]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [26]:
df

       Name    Age  Gender         City   Salary              Comment
0    Alice   25.00  Female     New York  50000.0            Good job!
1      @Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie$  35.00    Male     New York  58000.0            Paid $100
4      Eve%  28.00  Female      unknown  56000.0          Excellent!!
5    Frank*  -5.00    Male      Chicago  70000.0          Check* this

## Clean text data
### Inconsistent data

In [27]:
# remove leading/trailing spaces
df['Name'] = df['Name'].str.strip()

In [28]:
# remove special characters
df['Name'] = df['Name'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)

In [29]:
df

      Name    Age  Gender         City   Salary              Comment
0    Alice  25.00  Female     New York  50000.0            Good job!
1      Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie  35.00    Male     New York  58000.0            Paid $100
4      Eve  28.00  Female      unknown  56000.0          Excellent!!
5    Frank  -5.00    Male      Chicago  70000.0          Check* this

In [30]:
# Capitalize
df['Gender'] = df['Gender'].str.capitalize()

In [31]:
df

      Name    Age  Gender         City   Salary              Comment
0    Alice  25.00  Female     New York  50000.0            Good job!
1      Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie  35.00    Male     New York  58000.0            Paid $100
4      Eve  28.00  Female      unknown  56000.0          Excellent!!
5    Frank  -5.00    Male      Chicago  70000.0          Check* this

In [32]:
# proper case for cities
df['City'] = df['City'].str.title()

In [33]:
df

      Name    Age  Gender         City   Salary              Comment
0    Alice  25.00  Female     New York  50000.0            Good job!
1      Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie  35.00    Male     New York  58000.0            Paid $100
4      Eve  28.00  Female      Unknown  56000.0          Excellent!!
5    Frank  -5.00    Male      Chicago  70000.0          Check* this

## Handling invalid/inconsistent data

In [34]:
# filter rows with positive ages
df = df[df['Age'] > 0]

In [35]:
df

      Name    Age  Gender         City   Salary              Comment
0    Alice  25.00  Female     New York  50000.0            Good job!
1      Bob  20.75    Male  Los Angeles  60000.0  Needs improvement
2  Charlie  35.00    Male     New York  58000.0            Paid $100
4      Eve  28.00  Female      Unknown  56000.0          Excellent!!

### Converting Data Types

In [37]:
df.dtypes

Name        object
Age        float64
Gender      object
City        object
Salary     float64
Comment     object
dtype: object

In [38]:
# convert data types
df['Age'] = df['Age'].astype(int)
#df['Salary'] = df['Salary'].astype(int)

C:\Users\ABC\AppData\Local\Temp\ipykernel_24396\636337156.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].astype(int)

In [39]:
df.dtypes

Name        object
Age          int32
Gender      object
City        object
Salary     float64
Comment     object
dtype: object

In [40]:
df

      Name  Age  Gender         City   Salary              Comment
0    Alice   25  Female     New York  50000.0            Good job!
1      Bob   20    Male  Los Angeles  60000.0  Needs improvement
2  Charlie   35    Male     New York  58000.0            Paid $100
4      Eve   28  Female      Unknown  56000.0          Excellent!!

## Rename columns for consistency

In [41]:
# Rename columns for consistency
df.rename(columns={'Name': 'Employee_Name', 'Comment': 'Performance'}, inplace=True)

C:\Users\ABC\AppData\Local\Temp\ipykernel_24396\2586562462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Name': 'Employee_Name', 'Comment': 'Performance'}, inplace=True)

In [42]:
df

  Employee_Name  Age  Gender         City   Salary          Performance
0         Alice   25  Female     New York  50000.0            Good job!
1           Bob   20    Male  Los Angeles  60000.0  Needs improvement
2       Charlie   35    Male     New York  58000.0            Paid $100
4           Eve   28  Female      Unknown  56000.0          Excellent!!

## Final cleaned data

In [43]:
df

  Employee_Name  Age  Gender         City   Salary          Performance
0         Alice   25  Female     New York  50000.0            Good job!
1           Bob   20    Male  Los Angeles  60000.0  Needs improvement
2       Charlie   35    Male     New York  58000.0            Paid $100
4           Eve   28  Female      Unknown  56000.0          Excellent!!

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_Name  4 non-null      object
 1   Age            4 non-null      int32
 2   Gender         4 non-null      object
 3   City           4 non-null      object
 4   Salary         4 non-null      float64
 5   Performance    4 non-null      object
dtypes: float64(1), int32(1), object(4)
memory usage: 208.0+ bytes

### dealing with data that might contain non-numeric values (e.g., strings) in a column that should ideally be numerical.

In [45]:
ddf = pd.DataFrame({
    'Age': ['22', '44', 'twenty']
})

In this DataFrame the Column Age should be numeric but it is provide in strings.  
To convert string to numerical value and handling invalid number string such as 'twenty'

In [49]:
# coerce will handling invalid string and replace it with NaN
ddf = pd.to_numeric(ddf['Age'], errors='coerce')

In [50]:
ddf

0    22.0
1    44.0
2     NaN
Name: Age, dtype: float64

In [51]:
ddf1 = pd.DataFrame({
    'Age': [22,33,55],
    'Disease': [np.nan, np.nan, np.nan],
    'Remarks': [np.nan, np.nan, np.nan]
})

In [54]:
ddf1

   Age  Disease  Remarks
0   22      NaN      NaN
1   33      NaN      NaN
2   55      NaN      NaN

to drop specific columns

In [57]:
ddf1.drop(['Disease', 'Remarks'], axis=1, inplace=True)

In [58]:
ddf1

   Age
0   22
1   33
2   55