# Padas Tutorial 3:  
## Merge, Join, Concat

In [1]:
import pandas as pd

## Merging:
In pandas, merging is the process of combining/joining two or more Dataframes or Series based on common columns.  
It is similar to SQL database join

### Forms of joins:

1. inner join
2. outer join
3. left join
4. right join

In [2]:
# Creating dataFrames

# DataFrame 1 contains persons names with ids and ages
df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "Diana"],
    "age": [25, 30, 35, 40]
})

# DataFrame 2 contains persons IDs living in the city with income
df2 = pd.DataFrame({
    "id": [3, 4, 5, 6],
    "city": ["London", "Paris", "Berlin", "Rome"],
    "income": [70000, 80000, 50000, 60000]
})

df1, df2

(   id     name  age
 0   1    Alice   25
 1   2      Bob   30
 2   3  Charlie   35
 3   4    Diana   40,
    id    city  income
 0   3  London   70000
 1   4   Paris   80000
 2   5  Berlin   50000
 3   6    Rome   60000)

#### 1. Inner Join:  (Default)
Return only rows with matching keys in both DataFrames

In [3]:
inner_join = pd.merge(df1, df2, on='id')

In [4]:
inner_join

   id     name  age    city  income
0   3  Charlie   35  London   70000
1   4    Diana   40   Paris   80000

#### 2. Left Join:  
Combines two dataframes based on common keys, preserving all rows from the left dataframe and including matching rwos from the right dataframe

In [5]:
left_join = pd.merge(df1, df2, on='id', how='left')

In [6]:
left_join

   id     name  age    city   income
0   1    Alice   25     NaN      NaN
1   2      Bob   30     NaN      NaN
2   3  Charlie   35  London  70000.0
3   4    Diana   40   Paris  80000.0

#### 3. Right Join:
Combines two dataFrames based on common keys, preserving all rows from the right dataframe and including matching rows from the left dataframe

In [7]:
right_join = pd.merge(df1, df2, on='id', how='right')

In [8]:
right_join

   id     name   age    city  income
0   3  Charlie  35.0  London   70000
1   4    Diana  40.0   Paris   80000
2   5      NaN   NaN  Berlin   50000
3   6      NaN   NaN    Rome   60000

#### 4. Outer Join:
Combines all rows of both dataframes

In [9]:
outer_join = pd.merge(df1, df2, on='id', how='outer')

In [10]:
outer_join

   id     name   age    city   income
0   1    Alice  25.0     NaN      NaN
1   2      Bob  30.0     NaN      NaN
2   3  Charlie  35.0  London  70000.0
3   4    Diana  40.0   Paris  80000.0
4   5      NaN   NaN  Berlin  50000.0
5   6      NaN   NaN    Rome  60000.0

### Merge on columns with different names

In [11]:
df1 = df1.rename(columns={'id': 'left_id'})
df2 = df2.rename(columns={'id': 'right_id'})

In [12]:
df1, df2

(   left_id     name  age
 0        1    Alice   25
 1        2      Bob   30
 2        3  Charlie   35
 3        4    Diana   40,
    right_id    city  income
 0         3  London   70000
 1         4   Paris   80000
 2         5  Berlin   50000
 3         6    Rome   60000)

In [13]:
outer_join = pd.merge(df1, df2, left_on='left_id', right_on='right_id', how='outer')

In [14]:
outer_join

   left_id     name   age  right_id    city   income
0      1.0    Alice  25.0       NaN     NaN      NaN
1      2.0      Bob  30.0       NaN     NaN      NaN
2      3.0  Charlie  35.0       3.0  London  70000.0
3      4.0    Diana  40.0       4.0   Paris  80000.0
4      NaN      NaN   NaN       5.0  Berlin  50000.0
5      NaN      NaN   NaN       6.0    Rome  60000.0

### Merging using multiple keys

In [16]:
df3 = pd.DataFrame({
    "year":[2020,2020,2021],
    "country":["US","UK","US"],
    "val":[10,20,30]
})

df4 = pd.DataFrame({
    "year":[2020,2021],
    "country":["US","US"],
    "extra":[100,200]
})

In [23]:
left_join = pd.merge(df3, df4, on=['year', 'country'], how='outer')

In [24]:
left_join

   year country  val  extra
0  2020      UK   20    NaN
1  2020      US   10  100.0
2  2021      US   30  200.0

## Join:  
In pandas, .join() is used to combine columns of two dataframes base on their indexes

In [25]:
df1 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35]
}, index=["a", "b", "c"])

df2 = pd.DataFrame({
    "city": ["London", "Paris", "Berlin"],
    "salary": [70000, 80000, 65000]
}, index=["a", "b", "d"])

In [27]:
# defalut in left join
df1.join(df2)

      name  age    city   salary
a    Alice   25  London  70000.0
b      Bob   30   Paris  80000.0
c  Charlie   35     NaN      NaN

In [29]:
df1.join(df2, how='inner')

    name  age    city  salary
a  Alice   25  London   70000
b    Bob   30   Paris   80000

In [30]:
df1.join(df2, how='outer')

      name   age    city   salary
a    Alice  25.0  London  70000.0
b      Bob  30.0   Paris  80000.0
c  Charlie  35.0     NaN      NaN
d      NaN   NaN  Berlin  65000.0

In [31]:
df1.join(df2, how='right')

    name   age    city  salary
a  Alice  25.0  London   70000
b    Bob  30.0   Paris   80000
d    NaN   NaN  Berlin   65000

#### Join on specific column (instead of index)

In [33]:
left = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Alice", "Bob", "Charlie"]
})

right = pd.DataFrame({
    "id": [1, 2, 4],
    "city": ["London", "Paris", "Berlin"]
})


left.join(right.set_index('id'), on='id')

   id     name    city
0   1    Alice  London
1   2      Bob   Paris
2   3  Charlie     NaN

## concat:  
it is used to stack or combine multiple DataFrames or Series along a particular axis (rows or columns).

In [34]:
df1 = pd.DataFrame({
    "A": ["A0", "A1", "A2"],
    "B": ["B0", "B1", "B2"]
})

df2 = pd.DataFrame({
    "A": ["A3", "A4", "A5"],
    "B": ["B3", "B4", "B5"]
})

In [35]:
# vertical concatenation --> axis=0  (Default)
pd.concat([df1, df2])

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

In [36]:
# horizontal concatenation --> axis=1
pd.concat([df1, df2], axis=1)

    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

#### Concatenating with different columns

In [42]:
df3 = pd.DataFrame({
    "A": ["A0", "A7"],
    "C": ["C6", "C7"]
})

In [40]:
pd.concat([df1, df3])

    A    B    C
0  A0   B0  NaN
1  A1   B1  NaN
2  A2   B2  NaN
0  A0  NaN   C6
1  A7  NaN   C7